### ISSUE TITLE
Please, provide a working example

### ISSUE THREAD

**Issue by monkiki** [Deguang/vue-pdf-reader#5]
I've tried to use this component but failed with "Uncaught ReferenceError: Vue is not defined", so I would like a working sample. 

Regards.

**Comment by Deguang** [comment]
Thanks for your reply.
This repo has not synced to the correct version. I'll let it work properly on the weekend at the latest weekend.

**Comment by monkiki** [comment]
Thanks, I'll be watching.

**Comment by Deguang** [comment]
I've been update some dependencies, and `npm run dev` will start a demo for explore
