### ISSUE TITLE
set number of page

### ISSUE THREAD

**Issue by ongbona** [Deguang/vue-pdf-reader#7]
Please help me!
I want to set the number of pages.

**Comment by Deguang** [comment]
Do you want to show one special page or change any page with a pagination widget？

**Comment by ongbona** [comment]
@Deguang 
Yes That's true. change any page

**Comment by Deguang** [comment]
Currently, this component is used to show all pages for requirement of my project. I'll add this feature in future, but this need more jobs with no scheduled. Maybe this weekend, maybe next month.

**Comment by ongbona** [comment]
@Deguang 
Thank you !
If you do it soon and work well.I'll donate you some.

**Comment by Deguang** [comment]
@OngBona 
Fine, I'll do this job in the last two weeks.

**Comment by Deguang** [comment]
@OngBona 
I've been finished a primary version, you can pull the latest repo and run `npm run dev` for a demo.

**Comment by ongbona** [comment]
@Deguang How can I donate you?

**Comment by Deguang** [comment]
@OngBona How about alipay or wechat ?
Alipay: 
<img width="279" alt="alipay" src="https://user-images.githubusercontent.com/11596327/69944207-b4d23300-1521-11ea-9398-163ef4fcdd2f.png">
Wechat: 
<img width="257" alt="wechat" src="https://user-images.githubusercontent.com/11596327/69944208-b56ac980-1521-11ea-9ff2-8fe00ec0ea96.png">

**Comment by ongbona** [comment]
But I have no them. I use Visa card.

**Comment by ongbona** [comment]
But I try to register Alipay

**Comment by Deguang** [comment]
@OngBona Don't mind about this.
